server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tarifadb
    username: root
    password: copito
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/