server:
  port: 8080

# Puede que tenga que poner instance: hostname: localhost
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173, http://localhost:3000"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: descuentoGrupo
          uri: lb://KartingDescuentoGrupo
          predicates:
            - Path=/api/descuento-grupo/**

        - id: descuentoFrecuencia
          uri: lb://KartingDescuentoFrecuencia
          predicates:
            - Path=/api/descuento-frecuencia/**

        - id: descuentoDiaEspecial
          uri: lb://KartingDescuentoDiaEspecial
          predicates:
            - Path=/api/descuento-dia-especial/**

        - id: rack
          uri: lb://KartingRack
          predicates:
            - Path=/api/rack/**

        - id: reporte
          uri: lb://KartingReporte
          predicates:
           - Path=/api/reporte/**

        - id: tarifa
          uri: lb://KartingTarifa
          predicates:
            - Path=/api/tarifa/**

        - id: reserva
          uri: lb://KartingReserva
          predicates:
            - Path=/api/reserva/**

        - id: cliente
          uri: lb://KartingReserva
          predicates:
              - Path=/api/cliente/**

        - id: comprobante
          uri: lb://KartingReserva
          predicates:
              - Path=/api/comprobante/**