server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JosueUsach/KartingMicroServices
          default-label: master
          search-paths: config-data
  application:
    name: KartingConfigServer